export const TRANSACTIONS = [
  {
    id: 1,
    title: "Grocery Shopping",
    category: "Food & Dining",
    value: "45.20",
    createdAt: "2024-11-01",
  },
  {
    id: 2,
    title: "Monthly Rent",
    category: "Housing",
    value: "1200.00",
    createdAt: "2024-11-01",
  },
  {
    id: 3,
    title: "Uber Ride",
    category: "Transportation",
    value: "15.75",
    createdAt: "2024-11-03",
  },
  {
    id: 4,
    title: "Motorcycle Maintenance",
    category: "Vehicle Expenses",
    value: "150.00",
    createdAt: "2024-10-20",
  },
  {
    id: 5,
    title: "Bookstore Purchase",
    category: "Education",
    value: "32.99",
    createdAt: "2024-11-02",
  },
  {
    id: 6,
    title: "Pet Supplies",
    category: "Shopping",
    value: "45.00",
    createdAt: "2024-10-29",
  },
  {
    id: 7,
    title: "Internet Bill",
    category: "Utilities",
    value: "65.00",
    createdAt: "2024-10-25",
  },
  {
    id: 8,
    title: "Dinner at Restaurant",
    category: "Food & Dining",
    value: "85.50",
    createdAt: "2024-10-28",
  },
  {
    id: 9,
    title: "Gym Membership",
    category: "Health & Fitness",
    value: "50.00",
    createdAt: "2024-10-15",
  },
  {
    id: 10,
    title: "Electricity Bill",
    category: "Utilities",
    value: "120.00",
    createdAt: "2024-10-18",
  },
  {
    id: 11,
    title: "Movie Tickets",
    category: "Entertainment",
    value: "30.00",
    createdAt: "2024-10-30",
  },
  {
    id: 12,
    title: "Gas Station",
    category: "Transportation",
    value: "40.00",
    createdAt: "2024-11-04",
  },
  {
    id: 13,
    title: "Online Course",
    category: "Education",
    value: "120.00",
    createdAt: "2024-11-05",
  },
  {
    id: 14,
    title: "Pharmacy Purchase",
    category: "Health & Fitness",
    value: "15.30",
    createdAt: "2024-11-06",
  },
  {
    id: 15,
    title: "New Shoes",
    category: "Shopping",
    value: "75.00",
    createdAt: "2024-10-22",
  },
  {
    id: 16,
    title: "Streaming Service",
    category: "Entertainment",
    value: "12.99",
    createdAt: "2024-11-07",
  },
  {
    id: 17,
    title: "Water Bill",
    category: "Utilities",
    value: "30.00",
    createdAt: "2024-10-17",
  },
  {
    id: 18,
    title: "Car Insurance",
    category: "Vehicle Expenses",
    value: "300.00",
    createdAt: "2024-10-13",
  },
  {
    id: 19,
    title: "Birthday Gift",
    category: "Gifts",
    value: "50.00",
    createdAt: "2024-10-05",
  },
  {
    id: 20,
    title: "Coffee Shop",
    category: "Food & Dining",
    value: "5.50",
    createdAt: "2024-11-02",
  },
  {
    id: 21,
    title: "Electric Scooter Rental",
    category: "Transportation",
    value: "10.00",
    createdAt: "2024-10-24",
  },
  {
    id: 22,
    title: "Yoga Class",
    category: "Health & Fitness",
    value: "20.00",
    createdAt: "2024-11-09",
  },
  {
    id: 23,
    title: "Home Improvement",
    category: "Housing",
    value: "55.00",
    createdAt: "2024-10-12",
  },
  {
    id: 24,
    title: "Concert Tickets",
    category: "Entertainment",
    value: "80.00",
    createdAt: "2024-11-08",
  },
];

export const CATEGORIES = [
  { id: 1, name: "Technology" },
  { id: 2, name: "Science" },
  { id: 3, name: "Health" },
  { id: 4, name: "Sports" },
  { id: 6, name: "Vehicle Expenses" },
  { id: 7, name: "Food & Dining" },
  { id: 8, name: "Health & Fitness" },
  { id: 9, name: "Entertainment" },
  { id: 10, name: "Gifts" },
  { id: 11, name: "Housing" },
  { id: 12, name: "Education" },
  { id: 13, name: "Shopping" },
  { id: 14, name: "Transportation" },
  { id: 15, name: "Utilities" },
];
